open System
open System.IO
open System.Numerics

// DO NOT EDIT THIS FILE!!!
// This file contains the testing scripts for the program.
// The file you should edit is "Fibonacci.fs"
let timedTest() =
    printf "Running... "
    let start = DateTime.Now
    let stop = start + TimeSpan.FromSeconds(1)

    let mutable num = 0
    Fibonacci.testStart()
    while DateTime.Now < stop do
        Fibonacci.calculate(num) |> ignore
        num <- num + 1
    printfn "Done.\nResult: %d" (num - 1)

let timedTestDebug() =
    let output = new StreamWriter("timings.csv")
    output.WriteLine("Index,Time,Number")
    printf "Running... "

    let start = DateTime.Now
    let stop = start + TimeSpan.FromSeconds(1)

    let mutable num = 0
    Fibonacci.testStart()
    let mutable prev, result = (BigInteger.Zero, BigInteger.Zero)
    while DateTime.Now < stop do
        prev <- result
        result <- Fibonacci.calculate(num)
        num <- num + 1

        let now = DateTime.Now
        let time = now - start
        output.WriteLine($"{num},{time.TotalSeconds},{result}")
    output.Close()
    printfn "Done.\nResult: %d (Final Value %s)" (num - 1) (result.ToString())

[<EntryPoint>]
let main(_: string array) =
    printf "Press 1 for timed test, 2 for debug test (slightly slower) > "

    let mutable index = -1
    while index = -1 do
        index <- Console.ReadLine() |> int
        if (index = 1) then timedTest()
        elif (index = 2) then timedTestDebug()
        else
            printf "  Unknown > "
            index <- -1
    0
