using System.Numerics;

namespace FibonacciChallenge;

// DO NOT EDIT THIS FILE!!!
// This file contains the testing scripts for the program.
// The file you should edit is "Fibonacci.cs"
public static class Program
{
    public static void Main()
    {
        Console.Write("Press 1 for timed test, 2 for debug test (slightly slower) > ");
    _retry:
        int index = int.Parse(Console.ReadLine()!);
        switch (index)
        {
            case 1:
                TimedTest();
                break;

            case 2:
                TimedTestDebug();
                break;

            default:
                Console.Write("  Unknown > ");
                goto _retry;
        }
    }

    public static void TimedTest()
    {
        Fibonacci code = new();

        Console.Write("Running... ");
        DateTime start = DateTime.Now,
                 end = start + TimeSpan.FromSeconds(1);

        int num = 0;
        code.TestStart();
        while (DateTime.Now < end) code.Calculate(num++);
        Console.WriteLine($"Done.\nResult: {num - 1}");
    }
    public static void TimedTestDebug()
    {
        Fibonacci code = new();

        StreamWriter output = new("timings.csv");
        output.WriteLine("Index,Time,Number");
        Console.Write("Running... ");

        DateTime start = DateTime.Now,
                 end = start + TimeSpan.FromSeconds(1);

        int num = 0;
        code.TestStart();
        BigInteger prev = 0, result = 0;
        while (DateTime.Now < end)
        {
            output.Write(num);

            prev = result;
            result = code.Calculate(num++);

            DateTime now = DateTime.Now;
            TimeSpan time = now - start;
            output.WriteLine($",{time.TotalSeconds},{result}");
        }
        output.Close();
        Console.WriteLine($"Done.\nResult: {num - 1} (Final Value {prev}).");
    }
}
